### PR TITLE
Feature/wysiwyg bootstrap 3

### PR DESCRIPTION
**Pull request by brylie**
Replaced Summernote and x-editable-bootstrap with editable-text-wysiwyg-bootstrap-3. Created global editingThisCourseVar, and used throughout course page. Cleaned up template helpers. Refactored sidebar section and lesson add forms. Refactored lesson template.

### CODE REVIEW

**Comment by brylie** [comment]
@Crowducate/development please review and test this pull request.

**Comment by Rahbaran** [comment]
Looks great so far, some remarks:
1. if you try to save a lesson (by clicking on the disk icon), the editor closed and the lesson is not saved
2. I hit ENTER to add a lecture, but not to add a section. Would love to this option there, too.
3. Hitting Escape should close the editing mode.
4. To me it's a bit counter-intuitive to DOUBLE click on a lesson title for editing. I think one click would be enough.

Questions:
5. Is it possible to have the expanded view of the text editor as default? Maybe less tech-savvy people wouldn't see the arrow to expand the editor.
6. Is there any way to integrate in the editor-GUI an icon for embedding images?

Other than that, I'm really happy with the progress and the new editor seems to be great.

**Comment by brylie** [comment]
Some responses:
1. The save button on the rich text editor should now work, I just pushed a fix.
2. Hitting enter on section title should now work. I just pushed a fix.
3. Closing edit mode when 'Esc' is pressed is a feature request, and may need discussion.
4. The lesson title should be editable on single click, with a second click placing the text cursor in a location within the title string. If you are experiencing different results, please file an issue with specific steps to reproduce (including what browser/version you are using), so that we can track it.
5. There is an open [feature request](https://github.com/JackAdams/meteor-editable-text-wysiwyg-bootstrap-3/issues/2) in the [upstream package](https://github.com/JackAdams/meteor-editable-text-wysiwyg-bootstrap-3) issue queue for an option to show editor buttons by default.
6. There may already be image support (perhaps drag-and-drop), but it would be advisable to open a support request on the [upstream package](https://github.com/JackAdams/meteor-editable-text-wysiwyg-bootstrap-3) repository.

**Comment by Rahbaran** [comment]
Ok, all good now. Thanks :)

re 4: sorry, didn't describe it very well. 

What I meant was, it takes a double click to focus the LESSON (not the title) in the main frame. As a user I'd prefer when I click on the lesson title, the main frame _simultaneously_ changes to the lesson content which corresponds to the just clicked lesson title. It took me some time to figure out that I need to click twice for editing the lesson content. 

What do you think?

**Comment by brylie** [comment]
Our code does not directly work with the click events triggering the editable text, as they are part of the upstream package. Lets open a feature request in our project to discuss this feature and its implications. 

In the meantime, does this code seem possible to safely merge with the develop branch?

**Comment by Rahbaran** [comment]
Yes, so if this is the current case, I will merge now. Great work.

**Pull request merged**
